services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maquetador_sw
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend_container
    restart: always
    ports:
      - '80:80'
    environment:
      PORT: 80
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: maquetador_sw
      JWT_SECRET: flajeoitmcafejlgdfdkdhmhdfkdhmxkdhk7w838734ncryechkdhfsj

    depends_on:
      - postgres

volumes:
  postgres_data:
